# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true

# AndroidX package structure to make the build faster
android.useAndroidX=true
android.enableJetifier=true

# Use this property to suppress warnings about unsupported Gradle or Android Plugin versions.
android.suppressUnsupportedCompileSdk=35

# When set to true the Gradle daemon is to run the build with experimental ART-based tooling.
org.gradle.experimental.android.new-model=false

# Android architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# New Architecture - DISABLE
newArchEnabled=false

# Hermes Engine
hermesEnabled=true

# Disable auto-download of JDK
org.gradle.java.installations.auto-download=false